# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Compile with Maven
      run: mvn clean compile 
      
  test:
    needs: [compile]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Test with Maven
      run: mvn test

  package:
    needs: [test]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Package to .jar with maven
      run: |
        mvn package
        mkdir staging && cp target/*.jar staging
      
    - name: Repo content
      run: |
        ls -l 
        
  deploy:
    needs: [package]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Repo content
      run: |
        ls -l 
        
    - name: persist data workflow as artifact
      uses: actions/upload-artifact@v3
      with:
        name: github-action-artifact
        path: staging
